### ISSUE TITLE
JasonThink申请加入

### ISSUE THREAD

**Issue by jasonim** [itsCoder/weeklyblog#113]
Hi laobie，
Blog: http://hujiandong.com
本人是C/C++团队中Java最好的成员，Android团队中C/C++最好的。
希望加入一起成长， 具体可以看Blog的说明

Thanks

**Comment by itsMelo** [comment]
@jasonim  朋友你好，刚刚看到，请阅读一下 readme 的申请加入规范，并且提交 pr 吧

**Comment by itsMelo** [comment]
申请加入已经完成
