### ISSUE TITLE
网站RSS的支持问题

### ISSUE THREAD

**Issue by troyliu0105** [itsCoder/weeklyblog#123]
觉得可以加入RSS或邮件订阅的功能。。。 😄

**Comment by troyliu0105** [comment]
眼瞎。。。T-T

**Comment by laobie** [comment]
@troyliu0105 啊哈 我应该给个按钮暴露出来的

**Comment by laobie** [comment]
![image](https://cloud.githubusercontent.com/assets/7184320/20336337/50fa0602-ac04-11e6-8ce2-d09002727505.png)
暴露出来了 @troyliu0105

**Comment by troyliu0105** [comment]
wow。。。thx😂
