### ISSUE TITLE
申请加入该项目

### ISSUE THREAD

**Issue by ljuns** [itsCoder/weeklyblog#156]
你好，我叫李俊山，16年毕业，现在在广州某一传统企业撸代码。平常团队的移动端项目也不多，工作半年多来感觉自己没有学习到太多东西，没什么进步，给自己定了个小目标是今年上半年学习完《android 开发艺术探索》，同时每学习完一个章节就得写一篇总结。想要加入这个项目也是为了鞭策自己不断地去学习，不断地提升自己，希望可以加入该项目有机会和大家一起学习一起提升自我，谢谢。

博客地址：http://blog.csdn.net/ljuns

**Comment by ljuns** [comment]
补上个人博客地址：https://ljuns.github.io/

**Comment by itsMelo** [comment]
@ljuns  朋友加一下Q群 434187044
