### ISSUE TITLE
emilycyy apply to join the club

### ISSUE THREAD

**Issue by EmilyCYY** [itsCoder/weeklyblog#52]
android初级，爬坑中，求带，哈哈~~平时没什么爱好，就爱吃
目前在简书上发表博客：[http://www.jianshu.com/users/f56d0b0ab9b4/latest_articles](url)

**Comment by EmilyCYY** [comment]
[简书地址](http://www.jianshu.com/users/f56d0b0ab9b4/latest_articles)

**Comment by itsMelo** [comment]
提一下 readme 的 pr 加上自己名字的 member,参照加入规范

**Comment by EmilyCYY** [comment]
提了 不知道弄得对不对
