### ISSUE TITLE
Davidrou申请加入

### ISSUE THREAD

**Issue by Davidrou** [itsCoder/weeklyblog#61]
个人博客：[http://blog.csdn.net/Davidluo001]
从事android开发1年，希望共同进步。

**Comment by laobie** [comment]
根据我们的 readme 规则，个人的独立博客才行，建议你搭建个自己的博客，以后内容发布自己个人博客上。

**Comment by Davidrou** [comment]
@laobie 为什么要做这种限制呢？

**Comment by laobie** [comment]
我们的文章格式均是 markdown 格式的，协作基于 git，你拥有个人博客能证明你这些能力没问题。
