### ISSUE TITLE
ZetaoYang申请加入

### ISSUE THREAD

**Issue by ZetaoYang** [itsCoder/weeklyblog#96]
博客地址：https://zetaoyang.github.io （博客是由 Hego 生成的，由 GitLab-Cl 进行持续集成。）
 Hexo 这个静态网站生成器我也用过。站点是 https://www.codeomega.ga， 不过这个网站我已不放博文在上面了。
个人介绍：目前是一名大三学生，计算机专业。
在[众成翻译](http://zcfy.cc/)上翻译文章。这篇便是我翻译的：http://zcfy.cc/article/introducing-debugger-html-x2605-mozilla-hacks-8211-the-web-developer-blog-1346.html。

**Comment by laobie** [comment]
@ZetaoYang 不好意思，才处理这个。你发下 PR 就可以啦

**Comment by laobie** [comment]
@ZetaoYang 加一下 QQ 群 434187044

**Comment by ZetaoYang** [comment]
@laobie 这里的'PR'是什么意思？
